// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	aliyun "common/oss/api/internal/handler/aliyun"
	"common/oss/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sts",
				Handler: aliyun.StsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/aliyun"),
	)
}
